Added to social-apps.md: tumblr, pinterest, exercism, steam, ancestry.
Param302/SocialRepo pull request #34
Opened 2024-05-11 18:53 UTC by kimchiiboiii

# Title
Added to social-apps.md: tumblr, pinterest, exercism, steam, ancestry

## Description
Added 5 new social media websites with public profiles.
Profile URLs:
1. Steam: https://steamcommunity.com/id/**your-profile-url-here**/
2. Ancestry: https://www.ancestry.com/profile/**your-profile-url-here**
3. Tumblr: https://www.tumblr.com/**your-profile-url-here**
4. Pinterest: https://www.pinterest.com/**your-profile-url-here**/
5. Exercism: https://exercism.org/profiles/**your-profile-url-here**

---
## Issue Ticket Number
Fixes #29

---
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [X] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING](./docs/CONTRIBUTING)
- [X] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Param302/SocialRepo/pulls) for the same update/change?
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

2024-05-11 20:45 UTC, Param302 requested changes
Hey @kimchiiboiii ,
First of all thanks for your contribution!


Can you tell what is Ancestry and How it's public profile useful?

And
Please do the changes and let me know about Ancestry.

Also, make sure to follow basic guidelines, by discussion and asking to assigned the issue before working on.

As you've already raised the PR, and seeing your effort I will assign you the issue #29  . Please comment on the same so that I can assign you.

_Happy Contributing!_

2024-05-11 20:45 UTC, Param302 commented on .github/docs/social-apps.md
> +-   [x] Exercism
Just add the name of the app/website with `[ ]`, no need to check the checkbox, the checkbox is for some other purpose.

2024-05-12 02:36 UTC, kimchiiboiii commented
Hey, thanks so much.

Ancestry is a site where you can take a DNA test to get your ethnicity results, and map out your family tree, meet other users who have DNA matches with you.
However now that I think about it, there isn't much socializing besides the private messages and User Search feature.
Maybe at most you would just be messaging a distant cousin who has a DNA match with you, on that website.

So I think it's better for me to go ahead and replace it with Mastodon which is more used and definitely is a social media site.

2024-05-12 12:25 UTC, Param302 approved these changes
Hey @kimchiiboiii ,

Thanks for your valuable contribution to **SocialRepo**.

I am merging it to main branch

Looking forward for more contributions. :D
_Keep Contributing!_ 🙌

2024-05-12 12:26 UTC, merged