7 social media logos done
Param302/SocialRepo pull request #8
Opened 2024-05-07 00:00 UTC by evnxprk

# Title

## Description

---
## Issue Ticket Number
Fixes #(issue_number)

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING](./docs/CONTRIBUTING)
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Param302/SocialRepo/pulls) for the same update/change?
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

2024-05-07 09:45 UTC, Param302 commented
> # Title
> ## Description
> ## Issue Ticket Number
> 
> Fixes #(issue_number)

Also, specify the Title of the PR, Description of what have you changed, and Issue number so we can keep track off.

2024-05-07 09:46 UTC, Param302 requested changes
I have added the changes in comments.
Please check them and change accordingly.

And, I hope you are clear with the changes, if you have any confusions, feel free to ask.

_Happy Contributing_ 😊 🙌

2024-05-07 09:46 UTC, Param302 commented on src/assets/logos/discord.png
This discord icon seems to be of old version, please add the latest icon.

2024-05-07 09:46 UTC, Param302 commented on src/assets/logos/github.png
The github icon is black, not blue, please add the correct one 😅

2024-05-07 09:46 UTC, Param302 commented on src/social-links.json
> +    "gitlab": "https://www.gitlab.com/"
I guess, there's a confusion in the syntax 😅
All the links should be in one dictionary. Check syntax below 👇
```json
{
    "social_media_name": "link",
	"github": "https://github.com/"				// Example
    "linkedin": "https://www.linkedin.com/in/"	// Example
	
}
```

Like this.
The first line is just for the example, representing the **key** should contain the `social_media_name` and the **value** should contain `user profile prefix URL`.

Please add the links as specified in the above manner. Also, the keys should be in sorted alphabetically, so we can maintain an order.

I hope you are clear with the changes, if you have any confusions, feel free to ask.

_Happy Contributing_ 😊 🙌

2024-05-09 00:47 UTC, evnxprk commented
I have finished the changes that you've requested. As for the issue number, I'm unsure where that is located so I left it blank.

2024-05-09 07:41 UTC, Param302 requested changes
Hey,
Just change the github logo as specifiec. Rest is all good, then I will merge the PR.

_Thanks for putting so much effort and contributing_

2024-05-09 07:41 UTC, Param302 commented on src/assets/logos/github.png
The github logo is a little odd.
You can use github logo from [here](https://github.com/logos).

2024-05-10 01:41 UTC, evnxprk commented
I've fixed the github logo, let me know if this change is good to go.

2024-05-10 12:15 UTC, Param302 commented
Hey @evnxprk ,

## Amazing work done! ⭐
I am merging your PR to main branch.
Thanks for your contribution in **SocialRepo**

_Keep Contributing_ 🙌

2024-05-10 12:15 UTC, merged